#!/usr/bin/env bash

sudo -su liveuser yay -Sy --noconfirm --noeditmenu --nodiffmenu \
  mintlocale \
  simplenote-electron-bin \
  slack-desktop \
  etcher-bin \
  insomnia \
  pyenv \
  rbenv-git \
  ruby-build \
  nodenv \
  nodenv-node-build-git \
  debtap \
  google-talkplugin \
  ttf-ancient-fonts \
  curl \
  wget \
  unzip \
  git \
  ruby \
  python \
  python-pip \
  go \
  xclip \
  clipit \
  pandoc \
  lynx \
  neovim \
  terminator \
  docker \
  rsync \
  zsh \
  diffutils \
  chromium \
  vlc \
  visual-studio-code-bin \
  vagrant \
  clamtk \
  libu2f-host \
  keybase-gui \
  bzip2 \
  shfmt \
  zbar \
  ttf-hack \
  saw \
  cups \
  jq \
  tree \
  parallel \
  lastpass-cli \
  evopop-gtk-theme \
  evopop-icon-theme \
  materia-gtk-theme \
  psensor \
  bind-tools \
  jetbrains-toolbox \
  adobe-source-code-pro-fonts